"""
Final enrichment of parsed ENTSO-E data.
Supports multi-zone mapping (gen_zone vs price_zone) for accurate country referencing.
"""

from pathlib import Path
import pandas as pd
import sys

# -----------------------------
# 1. PATHS CONFIGURATION
# -----------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Reference data files
COUNTRIES_CSV = PROJECT_ROOT / "data" / "reference" / "countries.csv"
PSR_TYPES_CSV = PROJECT_ROOT / "data" / "reference" / "psr_types.csv"
BASE_PATH = PROJECT_ROOT / "data" / "processed"


# -----------------------------
# 2. ENRICHMENT LOGIC
# -----------------------------
def enrich_dataset(
    file_path: Path, countries_ref: pd.DataFrame, psr_ref: pd.DataFrame, category: str
):
    """
    Enriches the parsed data by merging it with country and PSR type references.
    Adapts the join key based on whether the data is 'prices' or 'generation'.
    """
    print(f"🔄 Processing {category}: {file_path.name}")

    # Load the parsed CSV (generated by the parsing script)
    df = pd.read_csv(file_path)

    # Ensure consistent data types for joining
    df["country"] = df["country"].astype(str)
    countries_ref["country"] = countries_ref["country"].astype(str)

    # 1. CATEGORY-SPECIFIC ENRICHMENT & COLUMN MAPPING
    if category == "prices":
        # For prices, we map the data using the price_zone EIC code
        enriched_df = df.merge(countries_ref, on="country", how="left")

        # Rename the 'value' column to be more descriptive
        enriched_df = enriched_df.rename(columns={"value": "price_eur"})

        # Select columns relevant for price analysis
        # We keep 'price_zone' as the reference bidding zone for this category
        final_cols = [
            "country",
            "country_name",
            "data_type",
            "price_zone",
            "start_time",
            "resolution",
            "position",
            "price_eur",
        ]
    else:  # generation
        # For generation, we map the data using the gen_zone EIC code
        enriched_df = df.merge(countries_ref, on="country", how="left")

        # Merge with PSR types reference to get readable technology names (e.g., Solar)
        enriched_df["psr_type"] = enriched_df["psr_type"].fillna("N/A").astype(str)
        psr_ref["psr_type"] = psr_ref["psr_type"].astype(str)

        enriched_df = enriched_df.merge(psr_ref, on="psr_type", how="left")
        enriched_df["generation_type"] = enriched_df["generation_type"].fillna(
            "Unknown/Other"
        )

        # Rename the 'value' column to indicate MegaWatts
        enriched_df = enriched_df.rename(columns={"value": "quantity_mw"})

        # Select columns relevant for generation analysis
        final_cols = [
            "country",
            "country_name",
            "data_type",
            "gen_zone",
            "psr_type",
            "generation_type",
            "start_time",
            "resolution",
            "position",
            "quantity_mw",
        ]

    # 2. FINAL CLEANUP
    # Handle missing names just in case a new country code appears
    enriched_df["country_name"] = enriched_df["country_name"].fillna("Unknown")

    # Filter to only include defined final columns
    enriched_df = enriched_df[final_cols]

    # Save the enriched file in the same directory as the parsed file
    output_path = file_path.parent / f"enriched_{category}.csv"
    enriched_df.to_csv(output_path, index=False)

    print(f"✅ Saved enriched {category} to: {output_path.absolute()}")
    return len(enriched_df)


# -----------------------------
# 3. MAIN EXECUTION
# -----------------------------
def main():
    # Handle execution date (from Airflow argument or default fallback)
    if len(sys.argv) > 1:
        target_date_raw = sys.argv[1]
        target_date = target_date_raw.replace("-", "/")
    else:
        target_date = "2026/02/01"

    print(f"🧩 Starting enrichment for date: {target_date}")

    # Load reference files into DataFrames
    try:
        countries_ref = pd.read_csv(COUNTRIES_CSV)
        psr_ref = pd.read_csv(PSR_TYPES_CSV)
    except Exception as e:
        print(f"❌ CRITICAL: Failed to load reference CSVs: {e}")
        sys.exit(1)

    categories = ["generation", "prices"]
    total_rows = 0

    # Process each category folder
    for cat in categories:
        input_file = BASE_PATH / cat / target_date / f"parsed_{cat}.csv"

        if input_file.exists():
            rows = enrich_dataset(input_file, countries_ref, psr_ref, cat)
            total_rows += rows
        else:
            print(f"⚠️ Parsed file not found: {input_file}")

    print(f"\n✨ Enrichment complete! Total rows processed: {total_rows}")


if __name__ == "__main__":
    main()
